apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  annotations:
    iconClass: icon-talos
    tags: hidden,kubevirt,talos
  generation: 1
  labels:
    app.kubernetes.io/component: kubevirt
    instancetype.kubevirt.io/common-instancetypes-version: v1.3.0
    instancetype.kubevirt.io/os-type: linux
    instancetype.kubevirt.io/vendor: kubevirt.io
  name: talos
spec:
  annotations:
    vm.kubevirt.io/os: linux
  devices:
    preferredDiskBus: virtio
    preferredInterfaceModel: virtio
    preferredRng: {}
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
